name: Hedron Archive

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Every 10 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write  # required to push and delete

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge all non-main branches into main
      run: |
        git checkout main
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -vE '^main$|^HEAD$'); do
          local_branch=${branch#origin/}
          echo "Merging branch $local_branch into main..."
          git merge --no-edit --allow-unrelated-histories origin/$local_branch || echo "Merge conflict or failure on $local_branch, skipping..."
        done

    - name: Push updated main
      run: git push origin main

    - name: Delete merged branches (except main)
      run: |
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -vE '^main$|^HEAD$'); do
          local_branch=${branch#origin/}
          echo "Deleting branch $local_branch..."
          git push origin --delete "$local_branch" || echo "Could not delete $local_branch"
        done
