name: hedron_archive

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write  # required to push and delete

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Extract pushed branch name
      id: vars
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

    - name: Checkout main
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch pushed branch
      run: |
        git fetch origin ${{ steps.vars.outputs.branch }}

    - name: Merge pushed branch into main
      run: |
        git checkout main
        git merge --no-edit --allow-unrelated-histories origin/${{ steps.vars.outputs.branch }}

    - name: Push merged main branch
      run: git push origin main

    - name: Delete merged branch
      run: git push origin --delete ${{ steps.vars.outputs.branch }}
